# Generated by Django 4.2.7 on 2025-07-09 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='machine',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Labels pour catégoriser la machine', to='machines.label', verbose_name='Labels'),
        ),
        migrations.AddField(
            model_name='machine',
            name='primary_muscles',
            field=models.ManyToManyField(help_text='Groupes musculaires principalement sollicités', related_name='primary_machines', to='machines.musclegroup', verbose_name='Muscles principaux'),
        ),
        migrations.AddField(
            model_name='machine',
            name='secondary_muscles',
            field=models.ManyToManyField(blank=True, help_text='Groupes musculaires secondairement sollicités', related_name='secondary_machines', to='machines.musclegroup', verbose_name='Muscles secondaires'),
        ),
        migrations.AlterUniqueTogether(
            name='machinerating',
            unique_together={('machine', 'user')},
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['machine_type'], name='machines_ma_machine_6b1bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['is_active', 'is_maintenance'], name='machines_ma_is_acti_1f8ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['popularity_score'], name='machines_ma_popular_1830d9_idx'),
        ),
    ]
