# Generated by Django 4.2.7 on 2025-07-09 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        ('calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.workouttemplate', verbose_name='Template de séance'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='workout_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workout', verbose_name='Séance créée'),
        ),
        migrations.AddField(
            model_name='weeklytemplate',
            name='friday_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_fridays', to='workouts.workouttemplate', verbose_name='Template du vendredi'),
        ),
        migrations.AddField(
            model_name='weeklytemplate',
            name='monday_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_mondays', to='workouts.workouttemplate', verbose_name='Template du lundi'),
        ),
        migrations.AddField(
            model_name='weeklytemplate',
            name='saturday_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_saturdays', to='workouts.workouttemplate', verbose_name='Template du samedi'),
        ),
        migrations.AddField(
            model_name='weeklytemplate',
            name='sunday_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_sundays', to='workouts.workouttemplate', verbose_name='Template du dimanche'),
        ),
        migrations.AddField(
            model_name='weeklytemplate',
            name='thursday_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_thursdays', to='workouts.workouttemplate', verbose_name='Template du jeudi'),
        ),
        migrations.AddField(
            model_name='weeklytemplate',
            name='tuesday_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_tuesdays', to='workouts.workouttemplate', verbose_name='Template du mardi'),
        ),
        migrations.AddField(
            model_name='weeklytemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_templates', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='weeklytemplate',
            name='wednesday_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_wednesdays', to='workouts.workouttemplate', verbose_name='Template du mercredi'),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_imports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.workout', verbose_name='Séance associée'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar.workoutplan', verbose_name='Plan associé'),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['user', 'scheduled_date'], name='calendar_wo_user_id_bbe261_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['is_active'], name='calendar_wo_is_acti_ca231b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'start_date'], name='calendar_ca_user_id_22d369_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type'], name='calendar_ca_event_t_7fae4a_idx'),
        ),
    ]
